<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/bootstrap.php';
$errors=[];$name='';$email='';$phone='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 require_csrf();$name=trim((string)($_POST['name']??''));$email=strtolower(trim((string)($_POST['email']??'')));$phone=trim((string)($_POST['phone']??''));$password=(string)($_POST['password']??'');$confirm=(string)($_POST['password_confirm']??'');
 if($name===''||mb_strlen($name)>120)$errors[]='Enter your name.'; if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>254)$errors[]='Enter a valid email address.'; if(strlen($password)<12)$errors[]='Use a password of at least 12 characters.'; if($password!==$confirm)$errors[]='Passwords do not match.';
 if(!$errors){$check=mysqli_prepare($link,'SELECT id FROM users WHERE email = ? LIMIT 1');mysqli_stmt_bind_param($check,'s',$email);mysqli_stmt_execute($check);if(mysqli_fetch_assoc(mysqli_stmt_get_result($check)))$errors[]='An account already exists for that email address.';}
 if(!$errors){$hash=password_hash($password,PASSWORD_DEFAULT);$stmt=mysqli_prepare($link,'INSERT INTO users (name,email,phone,password) VALUES (?,?,?,?)');mysqli_stmt_bind_param($stmt,'ssss',$name,$email,$phone,$hash);mysqli_stmt_execute($stmt);session_regenerate_id(true);$_SESSION['auth_id']=(int)mysqli_insert_id($link);$_SESSION['auth_email']=$email;$_SESSION['auth_name']=$name;header('Location: private.php');exit;}
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SkyMart - Register</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="assets/register.css"></head><body><main class="container py-5"><div class="row justify-content-center"><div class="col-12 col-md-8 col-lg-6"><div class="card"><div class="card-body p-5"><h1 class="h2 text-center mb-4">Create a SkyMart account</h1><?php if($errors): ?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errors as $error): ?><li><?= e($error) ?></li><?php endforeach; ?></ul></div><?php endif; ?><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="mb-3"><label class="form-label" for="name">Name</label><input id="name" name="name" value="<?= e($name) ?>" class="form-control" required maxlength="120"></div><div class="mb-3"><label class="form-label" for="email">Email</label><input id="email" type="email" name="email" value="<?= e($email) ?>" class="form-control" required maxlength="254"></div><div class="mb-3"><label class="form-label" for="phone">Phone (optional)</label><input id="phone" name="phone" value="<?= e($phone) ?>" class="form-control" maxlength="40"></div><div class="mb-3"><label class="form-label" for="password">Password</label><input id="password" type="password" name="password" class="form-control" required minlength="12"></div><div class="mb-4"><label class="form-label" for="password_confirm">Repeat password</label><input id="password_confirm" type="password" name="password_confirm" class="form-control" required minlength="12"></div><button class="btn btn-success w-100" type="submit">Register</button></form><p class="text-center mt-4 mb-0">Already registered? <a href="index.php">Login</a></p></div></div></div></div></main></body></html>
